### ISSUE TITLE
Using "pk" instead of "id" breaks it

### ISSUE THREAD

**Issue by vsego** [ericls/django-hashids#31]
Thank you for the awesome Django add-on!

The docs say:
> Proxy the internal model `pk` field without storing the value in the database

It really works very nice, except if
```python
hashid = HashidsField(real_field_name="id")
```
is replaced with
```python
hashid = HashidsField(real_field_name="pk")
```
in which case `User.objects.get(hashid="some value")` breaks with some cryptic `StopIteration` error.

Because `id` is a built-in Python function, I tend to always use `pk` for Django objects' Primary Key and I paid no attention to replacing `"id"` from your example with `"pk"`. That replacement is a habit, as it works everywhere (else). It took me quite a while to figure out why is my code above failing.

A simple workaround: add a warning to the docs.
A better solution: support `"pk"` as you do `"id"`.

**Comment by ericls** [comment]
Thanks for reporting the issue and proposed workaround. Gonna take a look when I find more time

**Comment by ericls** [comment]
hi @vsego , "pk" should be supported now. Also the error message would be less cryptic if a real_field can't be find.

**Comment by vsego** [comment]
@ericls, I didn't test it yet, but I did review the changes and it all looks good. Very nicely done. Thank you!
