### ISSUE TITLE
Usage sample with Django Rest Framework

### ISSUE THREAD

**Issue by parad0x96** [ericls/django-hashids#33]
Hello any idea how to use this library with DRF to encrypt/obfuscate `pk` especially with a viewset ex: `ModelViewSet`
Thanks in advance

**Comment by ericls** [comment]
Hi @parad0x96 , according to this issue #28 , looks like something similar to this would work
```
class TestModelViewSet(viewsets.ModelViewSet):
    lookup_field = "hashid"
```

Let me know if this doesn't cover your use case

**Comment by ericls** [comment]
Added a drf branch with some tests, seems like it's working
https://github.com/ericls/django-hashids/blob/drf/tests/test_app/drf.py

**Comment by parad0x96** [comment]
@ericls sorry for the late reply yes it helped me thank you
